export const USER = 'User';
export const UsersRepository = 'UsersRepository';
export const USER_ATTRIBUTES = ['id', 'username', 'createdAt', 'updatedAt'];
export const UserErrors = {
  USERNAME_REQUIRED: 'USERNAME_REQUIRED',
  USERNAME_LENGTH: 'USERNAME_LENGTH',
  USERNAME_UNIQUE: 'USERNAME_UNIQUE',
  EMAIL_REQUIRED: 'USERNAME_REQUIRED',
  EMAIL_LENGTH: 'USERNAME_LENGTH',
  EMAIL_UNIQUE: 'USERNAME_UNIQUE',
  INVALID_EMAIL: 'INVALID_EMAIL',
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  USER_NOT_FOUND: 'USER_NOT_FOUND'
};
