export enum Configurations {
  JWT_SECRET = 'JWT_SECRET',
  TOKEN_EXPIRATION_TIME = 'TOKEN_EXPIRATION_TIME',
  DEFAULT_LIMIT = 'DEFAULT_LIMIT',
  SUPERUSER_IDS = 'SUPERUSER_IDS',
  FIREBASE_BUCKET_PATH = 'FIREBASE_BUCKET_PATH'
}
